import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import * as ts from 'typescript';

import type { ComponentDoc } from './component-docs';

export type ComponentExampleDoc = {
  code: string;
  exportName: string;
  title: string;
};

export type ComponentPropDoc = {
  defaultValue: string | null;
  description: string | null;
  name: string;
  required: boolean;
  type: string;
};

export type GeneratedComponentRegistryEntry = {
  description: string | null;
  docsPath: string;
  examples: ComponentExampleDoc[];
  href: string;
  inheritedPropsNote: string | null;
  props: ComponentPropDoc[];
  slug: string;
  sourcePath: string;
  status: string | null;
  storyPath: string | null;
  storybookTitle: string | null;
  swiftui: string | null;
  title: string;
};

type PreviewModuleEntry = {
  slug: string;
  source: string;
};

const registryHeader = `/* eslint-disable */
/* auto-generated by apps/docs/scripts/generate-docs-content.ts */
`;

function getSiblingPath(sourcePath: string, extension: string) {
  const baseName = sourcePath.replace(/\.docs\.mdx$/, '');
  return `${baseName}${extension}`;
}

function fileExists(sourcePath: string) {
  return readFile(sourcePath, 'utf8')
    .then(() => true)
    .catch(() => false);
}

function prettifyExportName(name: string) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/_/g, ' ')
    .trim();
}

function parseCanvasExamples(source: string, storySource: string | null): ComponentExampleDoc[] {
  const lines = source.split('\n');
  const headings: Array<{ level: number; value: string }> = [];
  const examples: ComponentExampleDoc[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    const headingMatch = line.match(/^(#{2,6})\s+(.+)$/);

    if (headingMatch) {
      const level = headingMatch[1].length;
      while (headings.length > 0 && headings.at(-1)!.level >= level) {
        headings.pop();
      }
      headings.push({ level, value: headingMatch[2].trim() });
      continue;
    }

    const canvasMatch = line.match(/^<Canvas\s+of=\{([^}]+)\}\s*\/>$/);
    if (!canvasMatch) {
      continue;
    }

    const expression = canvasMatch[1].trim();
    const exportName = expression.split('.').at(-1) ?? expression;
    const heading = headings
      .slice()
      .reverse()
      .find((entry) => !/^usage$/i.test(entry.value));

    examples.push({
      code: storySource ? extractStoryCode(storySource, exportName) : '',
      exportName,
      title: heading?.value ?? prettifyExportName(exportName),
    });
  }

  return examples;
}

export function extractStoryCode(storySource: string, exportName: string) {
  const startToken = `export const ${exportName}`;
  const startIndex = storySource.indexOf(startToken);

  if (startIndex < 0) {
    return '';
  }

  const nextExportIndex = storySource.indexOf('\nexport const ', startIndex + startToken.length);
  const nextDefaultIndex = storySource.indexOf('\nexport default', startIndex + startToken.length);
  const endIndexCandidates = [nextExportIndex, nextDefaultIndex].filter((value) => value >= 0);
  const endIndex =
    endIndexCandidates.length > 0 ? Math.min(...endIndexCandidates) : storySource.length;

  return storySource.slice(startIndex, endIndex).trim();
}

function rewriteImportSpecifiers(specifiers: string) {
  return specifiers
    .split(',')
    .map((specifier) => specifier.trim())
    .filter(Boolean)
    .filter((specifier) => !specifier.startsWith('type '))
    .filter((specifier) => !/^I[A-Z].*Props$/.test(specifier))
    .join(', ');
}

async function loadUiRootExports(previewDir: string) {
  const distIndexPath = join(previewDir, '../../../../packages/ui/dist/index.js');

  const source = await readFile(distIndexPath, 'utf8').catch(() => null);
  if (!source) {
    return new Set<string>();
  }

  const blockMatch = source.match(/export\s*\{([\s\S]*?)\};/);
  if (!blockMatch) {
    return new Set<string>();
  }

  const exports = new Set<string>();
  const exportPattern = /\bas\s+([A-Za-z$_][\w$]*)/g;

  for (const match of blockMatch[1].matchAll(exportPattern)) {
    exports.add(match[1]);
  }

  return exports;
}

function extractUiImports(source: string, uiImportPath: string) {
  const imports = new Set<string>();
  const escapedPath = uiImportPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const importPattern = new RegExp(`import\\s+\\{([^}]+)\\}\\s+from\\s+['"]${escapedPath}['"]`, 'g');

  for (const match of source.matchAll(importPattern)) {
    const specifiers = match[1]
      .split(',')
      .map((specifier) => specifier.trim())
      .filter(Boolean);

    for (const specifier of specifiers) {
      if (/^I[A-Z].*Props$/.test(specifier)) {
        continue;
      }
      imports.add(specifier);
    }
  }

  return imports;
}

export function transformStorySourceForDocs(source: string, uiImportPath: string) {
  return source
    .replace(/^import\s+type\s+\{[^}]+\}\s+from\s+['"]@storybook\/react(?:-vite)?['"]\s*;?\s*$/gm, '')
    .replace(/^import\s+\{[^}]+\}\s+from\s+['"]@storybook\/react(?:-vite)?['"]\s*;?\s*$/gm, '')
    .replace(/^import\s+.+from\s+['"][^'"]+\.mdx['"]\s*;?\s*$/gm, '')
    .replace(
      /^import\s+\{([^}]+)\}\s+from\s+['"](\.{1,2}\/[^'"]*|\.)['"]\s*;?\s*$/gm,
      (_, specifiers: string) => {
        const rewritten = rewriteImportSpecifiers(specifiers);
        return rewritten ? `import { ${rewritten} } from '${uiImportPath}'` : '';
      },
    )
    .replace(/^const meta:\s*Meta<[\s\S]*?^export default meta\s*$/gm, '')
    .replace(/^type Story\s*=\s*StoryObj<[\s\S]*?^\s*$/gm, '')
    .replace(/export const (\w+)\s*:\s*Story\s*=/g, 'export const $1 =')
    .trim();
}

export function extractMetaComponent(source: string) {
  const match = source.match(/component:\s*([A-Za-z$_][\w$]*)/);
  return match?.[1] ?? null;
}

function extractMetaValue(source: string, key: string) {
  const match = source.match(new RegExp(`${key}:\\s*'([^']+)'`));
  return match?.[1] ?? null;
}

function extractStorybookTitle(source: string | null) {
  if (!source) {
    return null;
  }

  const match = source.match(/title:\s*['"`]([^'"`]+)['"`]/);
  return match?.[1] ?? null;
}

function getNodeDescription(node: ts.Node) {
  const comments = ts.getJSDocCommentsAndTags(node);
  const parts: string[] = [];

  for (const comment of comments) {
    if (ts.isJSDoc(comment) && typeof comment.comment === 'string') {
      parts.push(comment.comment.trim());
    }
  }

  const description = parts.join('\n').trim();
  return description.length > 0 ? description : null;
}

function getNodeDefaultValue(node: ts.Node) {
  for (const tag of ts.getJSDocTags(node)) {
    if (tag.tagName.text !== 'default') {
      continue;
    }

    const value = typeof tag.comment === 'string' ? tag.comment : tag.comment?.map((part) => part.text).join('');
    const normalised = value?.trim();
    if (normalised) {
      return normalised;
    }
  }

  return null;
}

function extractPropsFromComponentSource(sourcePath: string, componentName: string) {
  const source = ts.sys.readFile(sourcePath);
  if (!source) {
    return {
      inheritedPropsNote: null,
      props: [] as ComponentPropDoc[],
    };
  }

  const sourceFile = ts.createSourceFile(sourcePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const targetNames = new Set([
    `I${componentName.replace(/\s+/g, '')}Props`,
    `${componentName.replace(/\s+/g, '')}Props`,
  ]);

  let inheritedPropsNote: string | null = null;
  const props: ComponentPropDoc[] = [];

  const visit = (node: ts.Node) => {
    if ((ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) && targetNames.has(node.name.text)) {
      if (ts.isInterfaceDeclaration(node)) {
        inheritedPropsNote =
          node.heritageClauses
            ?.flatMap((clause) => clause.types.map((typeNode) => typeNode.getText(sourceFile)))
            .join(', ') ?? null;

        for (const member of node.members) {
          if (!ts.isPropertySignature(member) || !member.name) {
            continue;
          }

          props.push({
            defaultValue: getNodeDefaultValue(member),
            description: getNodeDescription(member),
            name: member.name.getText(sourceFile).replace(/['"]/g, ''),
            required: !member.questionToken,
            type: member.type?.getText(sourceFile) ?? 'unknown',
          });
        }
      } else if (ts.isTypeLiteralNode(node.type)) {
        for (const member of node.type.members) {
          if (!ts.isPropertySignature(member) || !member.name) {
            continue;
          }

          props.push({
            defaultValue: getNodeDefaultValue(member),
            description: getNodeDescription(member),
            name: member.name.getText(sourceFile).replace(/['"]/g, ''),
            required: !member.questionToken,
            type: member.type?.getText(sourceFile) ?? 'unknown',
          });
        }
      } else {
        inheritedPropsNote = node.type.getText(sourceFile);
      }
    }

    ts.forEachChild(node, visit);
  };

  visit(sourceFile);

  return {
    inheritedPropsNote,
    props,
  };
}

async function buildComponentRegistryEntries(componentDocs: ComponentDoc[]) {
  return Promise.all(
    componentDocs.map(async (doc) => {
      const docsSource = await readFile(doc.sourcePath, 'utf8');
      const storyPath = getSiblingPath(doc.sourcePath, '.stories.tsx');
      const componentDir = dirname(doc.sourcePath);
      const indexPath = join(componentDir, 'index.tsx');
      const fallbackIndexPath = join(componentDir, 'index.ts');
      const typesPath = join(componentDir, 'types.ts');

      const resolvedSourcePath = (await fileExists(indexPath)) ? indexPath : fallbackIndexPath;
      const hasStory = await fileExists(storyPath);
      const storySource = hasStory ? await readFile(storyPath, 'utf8') : null;
      const typesSource = (await fileExists(typesPath)) ? await readFile(typesPath, 'utf8') : '';
      const { props, inheritedPropsNote } = extractPropsFromComponentSource(
        resolvedSourcePath,
        doc.title,
      );

      return {
        description: doc.description,
        docsPath: doc.sourcePath,
        examples: parseCanvasExamples(docsSource, storySource),
        href: doc.href,
        inheritedPropsNote,
        props,
        slug: doc.slug,
        sourcePath: resolvedSourcePath,
        status: extractMetaValue(typesSource, 'status'),
        storyPath: hasStory ? storyPath : null,
        storybookTitle: extractStorybookTitle(storySource),
        swiftui: extractMetaValue(typesSource, 'swiftui'),
        title: doc.title,
      } satisfies GeneratedComponentRegistryEntry;
    }),
  );
}

async function buildPreviewModules(entries: GeneratedComponentRegistryEntry[], previewDir: string) {
  const previews: PreviewModuleEntry[] = [];
  const uiRootExports = await loadUiRootExports(previewDir);

  for (const entry of entries) {
    if (!entry.storyPath) {
      continue;
    }

    const storySource = await readFile(entry.storyPath, 'utf8');
    const previewFilePath = join(previewDir, `${entry.slug}.tsx`);
    const uiImportPath = relative(dirname(previewFilePath), join(previewDir, '../../../../packages/ui/dist/index.js'))
      .replaceAll('\\', '/')
      .replace(/\.js$/, '');
    const safeUiImportPath = uiImportPath.startsWith('.') ? uiImportPath : `./${uiImportPath}`;
    const transformed = transformStorySourceForDocs(
      storySource,
      safeUiImportPath,
    );
    const importedSymbols = extractUiImports(transformed, safeUiImportPath);
    const metaComponent = extractMetaComponent(storySource);

    if ([...importedSymbols].some((symbol) => !uiRootExports.has(symbol))) {
      continue;
    }

    if (metaComponent && !uiRootExports.has(metaComponent)) {
      continue;
    }

    previews.push({
      slug: entry.slug,
      source: `// @ts-nocheck\n'use client';\n\n${transformed}${
        metaComponent ? `\n\nexport const __DOCS_COMPONENT__ = ${metaComponent};` : ''
      }`,
    });
  }

  return previews;
}

export async function writeComponentRegistry(options: {
  componentDocs: ComponentDoc[];
  outputPath: string;
  previewDir: string;
}) {
  const entries = await buildComponentRegistryEntries(options.componentDocs);
  const previews = await buildPreviewModules(entries, options.previewDir);
  const previewLookup = new Map(previews.map((preview) => [preview.slug, `() => import('./previews/${preview.slug}')`]));
  const registryObject = Object.fromEntries(entries.map((entry) => [entry.slug, entry]));

  await mkdir(options.previewDir, { recursive: true });
  await Promise.all(
    previews.map(async (preview) => {
      await mkdir(join(options.previewDir, dirname(preview.slug)), { recursive: true });
      await writeFile(join(options.previewDir, `${preview.slug}.tsx`), `${preview.source}\n`);
    }),
  );

  const body = [
    registryHeader,
    `export const componentDocRegistry = ${JSON.stringify(registryObject, null, 2)} as const;`,
    '',
    'export const componentPreviewRegistry = {',
    ...entries.map((entry) => {
      const preview = previewLookup.get(entry.slug);
      return `  '${entry.slug}': ${preview ?? 'null'},`;
    }),
    '} as const;',
    '',
  ].join('\n');

  await mkdir(dirname(options.outputPath), { recursive: true });
  await writeFile(options.outputPath, body);
}
