import { readFile, writeFile, mkdir, rename } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import * as ts from 'typescript';

import type { ComponentDoc } from './component-docs';

export type ComponentExampleDoc = {
  code: string;
  exportName: string;
  title: string;
};

export type ComponentPropDoc = {
  defaultValue: string | null;
  description: string | null;
  name: string;
  required: boolean;
  type: string;
};

export type GeneratedComponentRegistryEntry = {
  description: string | null;
  docsPath: string;
  examples: ComponentExampleDoc[];
  href: string;
  inheritedPropsNote: string | null;
  props: ComponentPropDoc[];
  slug: string;
  sourcePath: string;
  status: string | null;
  storyPath: string | null;
  storybookTitle: string | null;
  swiftui: string | null;
  title: string;
};

type PreviewModuleEntry = {
  slug: string;
  source: string;
};

const registryHeader = `/* eslint-disable */
/* auto-generated by apps/docs/scripts/generate-docs-content.ts */
`;

async function writeFileAtomic(filePath: string, source: string) {
  const tempPath = `${filePath}.tmp`;
  await writeFile(tempPath, source);
  await rename(tempPath, filePath);
}

function getSiblingPath(sourcePath: string, extension: string) {
  const baseName = sourcePath.replace(/\.docs\.mdx$/, '');
  return `${baseName}${extension}`;
}

function fileExists(sourcePath: string) {
  return readFile(sourcePath, 'utf8')
    .then(() => true)
    .catch(() => false);
}

function prettifyExportName(name: string) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/_/g, ' ')
    .trim();
}

function parseCanvasExamples(source: string, storySource: string | null, componentName: string | null): ComponentExampleDoc[] {
  const lines = source.split('\n');
  const headings: Array<{ level: number; value: string }> = [];
  const examples: ComponentExampleDoc[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    const headingMatch = line.match(/^(#{2,6})\s+(.+)$/);

    if (headingMatch) {
      const level = headingMatch[1].length;
      while (headings.length > 0 && headings.at(-1)!.level >= level) {
        headings.pop();
      }
      headings.push({ level, value: headingMatch[2].trim() });
      continue;
    }

    const canvasMatch = line.match(/^<Canvas\s+of=\{([^}]+)\}\s*\/>$/);
    if (!canvasMatch) {
      continue;
    }

    const expression = canvasMatch[1].trim();
    const exportName = expression.split('.').at(-1) ?? expression;
    const heading = headings
      .slice()
      .reverse()
      .find((entry) => !/^usage$/i.test(entry.value));

    examples.push({
      code: storySource ? extractStoryCode(storySource, exportName, componentName ?? undefined) : '',
      exportName,
      title: heading?.value ?? prettifyExportName(exportName),
    });
  }

  return examples;
}

function unwrapRenderBody(body: ts.ConciseBody, sourceFile: ts.SourceFile) {
  if (ts.isBlock(body)) {
    const returnStatement = body.statements.find(ts.isReturnStatement);
    const expression = returnStatement?.expression;
    return expression ? expression.getText(sourceFile).trim().replace(/^\(([\s\S]*)\)$/, '$1').trim() : '';
  }

  return body.getText(sourceFile).trim().replace(/^\(([\s\S]*)\)$/, '$1').trim();
}

function getDemoComponentName(body: ts.ConciseBody) {
  if (!ts.isJsxSelfClosingElement(body) && !ts.isJsxElement(body)) {
    return null;
  }

  const openingElement = ts.isJsxElement(body) ? body.openingElement : body;
  if (!ts.isIdentifier(openingElement.tagName) || openingElement.attributes.properties.length > 0) {
    return null;
  }

  return openingElement.tagName.text;
}

function extractLocalComponentSource(sourceFile: ts.SourceFile, componentName: string) {
  for (const statement of sourceFile.statements) {
    if (ts.isFunctionDeclaration(statement) && statement.name?.text === componentName) {
      return statement.getText(sourceFile).trim();
    }

    if (!ts.isVariableStatement(statement)) {
      continue;
    }

    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || declaration.name.text !== componentName || !declaration.initializer) {
        continue;
      }

      if (ts.isArrowFunction(declaration.initializer) || ts.isFunctionExpression(declaration.initializer)) {
        return statement.getText(sourceFile).trim();
      }
    }
  }

  return null;
}

function isRenderFunction(
  value: ts.Expression,
): value is ts.ArrowFunction | ts.FunctionExpression {
  return ts.isArrowFunction(value) || ts.isFunctionExpression(value);
}

function isRenderProperty(
  property: ts.ObjectLiteralElementLike,
): property is ts.PropertyAssignment & {
  initializer: ts.ArrowFunction | ts.FunctionExpression;
} {
  return (
    ts.isPropertyAssignment(property) &&
    ts.isIdentifier(property.name) &&
    property.name.text === 'render' &&
    isRenderFunction(property.initializer)
  );
}

function isRenderMethod(
  property: ts.ObjectLiteralElementLike,
): property is ts.MethodDeclaration {
  return ts.isMethodDeclaration(property) && ts.isIdentifier(property.name) && property.name.text === 'render';
}

function isArgsProperty(
  property: ts.ObjectLiteralElementLike,
): property is ts.PropertyAssignment & {
  initializer: ts.ObjectLiteralExpression;
} {
  return (
    ts.isPropertyAssignment(property) &&
    ts.isIdentifier(property.name) &&
    property.name.text === 'args' &&
    ts.isObjectLiteralExpression(property.initializer)
  );
}

function formatJsxAttribute(name: string, value: ts.Expression, sourceFile: ts.SourceFile) {
  if (value.kind === ts.SyntaxKind.TrueKeyword) {
    return name;
  }

  if (ts.isStringLiteral(value) || ts.isNoSubstitutionTemplateLiteral(value)) {
    return `${name}=${JSON.stringify(value.text)}`;
  }

  return `${name}={${value.getText(sourceFile)}}`;
}

function buildArgsStoryCode(componentName: string, argsLiteral: ts.ObjectLiteralExpression, sourceFile: ts.SourceFile) {
  const attributes: string[] = [];
  let children: string | null = null;

  for (const property of argsLiteral.properties) {
    if (!ts.isPropertyAssignment(property) || !ts.isIdentifier(property.name)) {
      continue;
    }

    const propName = property.name.text;
    if (propName === 'children') {
      if (ts.isStringLiteral(property.initializer) || ts.isNoSubstitutionTemplateLiteral(property.initializer)) {
        children = property.initializer.text;
      } else {
        children = `{${property.initializer.getText(sourceFile)}}`;
      }
      continue;
    }

    attributes.push(formatJsxAttribute(propName, property.initializer, sourceFile));
  }

  const openingTag = attributes.length > 0 ? `<${componentName} ${attributes.join(' ')}>` : `<${componentName}>`;
  return children === null ? `${openingTag}</${componentName}>` : `${openingTag}${children}</${componentName}>`;
}

export function extractStoryCode(storySource: string, exportName: string, componentName?: string) {
  const sourceFile = ts.createSourceFile('story.tsx', storySource, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);

  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue;
    }

    if (!statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword)) {
      continue;
    }

    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || declaration.name.text !== exportName || !declaration.initializer) {
        continue;
      }

      if (!ts.isObjectLiteralExpression(declaration.initializer)) {
        return declaration.initializer.getText(sourceFile).trim();
      }

      const renderProperty = declaration.initializer.properties.find(isRenderProperty);
      const renderMethod = declaration.initializer.properties.find(isRenderMethod);

      if (renderProperty) {
        const demoComponentName = getDemoComponentName(renderProperty.initializer.body);
        if (demoComponentName) {
          const localComponentSource = extractLocalComponentSource(sourceFile, demoComponentName);
          if (localComponentSource) {
            return localComponentSource;
          }
        }

        return unwrapRenderBody(renderProperty.initializer.body, sourceFile);
      }

      if (renderMethod && renderMethod.body) {
        const demoComponentName = getDemoComponentName(renderMethod.body);
        if (demoComponentName) {
          const localComponentSource = extractLocalComponentSource(sourceFile, demoComponentName);
          if (localComponentSource) {
            return localComponentSource;
          }
        }

        return unwrapRenderBody(renderMethod.body, sourceFile);
      }

      const argsProperty = declaration.initializer.properties.find(isArgsProperty);

      if (argsProperty && componentName) {
        return buildArgsStoryCode(componentName, argsProperty.initializer, sourceFile);
      }
    }
  }

  return '';
}

function rewriteImportSpecifiers(specifiers: string) {
  return specifiers
    .split(',')
    .map((specifier) => specifier.trim())
    .filter(Boolean)
    .filter((specifier) => !specifier.startsWith('type '))
    .filter((specifier) => !/^I[A-Z].*Props$/.test(specifier))
    .join(', ');
}

async function resolveTsModulePath(basePath: string, specifier: string) {
  const candidates = [
    join(dirname(basePath), `${specifier}.ts`),
    join(dirname(basePath), `${specifier}.tsx`),
    join(dirname(basePath), specifier, 'index.ts'),
    join(dirname(basePath), specifier, 'index.tsx'),
  ];

  for (const candidate of candidates) {
    if (await fileExists(candidate)) {
      return candidate;
    }
  }

  return null;
}

async function collectExportsFromSourceFile(filePath: string, visited = new Set<string>()) {
  if (visited.has(filePath)) {
    return new Set<string>();
  }

  visited.add(filePath);
  const source = await readFile(filePath, 'utf8').catch(() => null);
  if (!source) {
    return new Set<string>();
  }

  const sourceFile = ts.createSourceFile(filePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const exports = new Set<string>();

  for (const statement of sourceFile.statements) {
    if (
      (ts.isVariableStatement(statement) || ts.isFunctionDeclaration(statement) || ts.isClassDeclaration(statement))
      && statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword)
    ) {
      if (ts.isVariableStatement(statement)) {
        for (const declaration of statement.declarationList.declarations) {
          if (ts.isIdentifier(declaration.name)) {
            exports.add(declaration.name.text);
          }
        }
      } else if (statement.name) {
        exports.add(statement.name.text);
      }
    }

    if (!ts.isExportDeclaration(statement) || !statement.moduleSpecifier) {
      continue;
    }

    const specifier = ts.isStringLiteral(statement.moduleSpecifier) ? statement.moduleSpecifier.text : null;
    if (!specifier?.startsWith('.')) {
      continue;
    }

    if (statement.exportClause && ts.isNamedExports(statement.exportClause)) {
      for (const element of statement.exportClause.elements) {
        exports.add(element.name.text);
      }
      continue;
    }

    const resolvedPath = await resolveTsModulePath(filePath, specifier);
    if (!resolvedPath) {
      continue;
    }

    const nestedExports = await collectExportsFromSourceFile(resolvedPath, visited);
    for (const exportedName of nestedExports) {
      exports.add(exportedName);
    }
  }

  return exports;
}

async function loadUiRootExports(previewDir: string) {
  const sourceIndexPath = join(previewDir, '../../../../packages/ui/src/index.tsx');
  if (await fileExists(sourceIndexPath)) {
    const sourceExports = await collectExportsFromSourceFile(sourceIndexPath);
    if (sourceExports.size > 0) {
      return sourceExports;
    }
  }

  const distIndexPath = join(previewDir, '../../../../packages/ui/dist/index.js');
  const distSource = await readFile(distIndexPath, 'utf8').catch(() => null);
  if (!distSource) {
    return new Set<string>();
  }

  const blockMatch = distSource.match(/export\s*\{([\s\S]*?)\};/);
  if (!blockMatch) {
    return new Set<string>();
  }

  const exports = new Set<string>();
  const exportPattern = /\bas\s+([A-Za-z$_][\w$]*)/g;

  for (const match of blockMatch[1].matchAll(exportPattern)) {
    exports.add(match[1]);
  }

  return exports;
}

function extractUiImports(source: string, uiImportPath: string) {
  const imports = new Set<string>();
  const escapedPath = uiImportPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const importPattern = new RegExp(`import\\s+\\{([^}]+)\\}\\s+from\\s+['"]${escapedPath}['"]`, 'g');

  for (const match of source.matchAll(importPattern)) {
    const specifiers = match[1]
      .split(',')
      .map((specifier) => specifier.trim())
      .filter(Boolean);

    for (const specifier of specifiers) {
      if (/^I[A-Z].*Props$/.test(specifier)) {
        continue;
      }
      imports.add(specifier);
    }
  }

  return imports;
}

export function transformStorySourceForDocs(source: string, uiImportPath: string) {
  return source
    .replace(/^import\s+type\s+\{[^}]+\}\s+from\s+['"]@storybook\/react(?:-vite)?['"]\s*;?\s*$/gm, '')
    .replace(/^import\s+\{[^}]+\}\s+from\s+['"]@storybook\/react(?:-vite)?['"]\s*;?\s*$/gm, '')
    .replace(/^import\s+.+from\s+['"][^'"]+\.mdx['"]\s*;?\s*$/gm, '')
    .replace(
      /^import\s+\{([^}]+)\}\s+from\s+['"](\.{1,2}\/[^'"]*|\.)['"]\s*;?\s*$/gm,
      (_, specifiers: string) => {
        const rewritten = rewriteImportSpecifiers(specifiers);
        return rewritten ? `import { ${rewritten} } from '${uiImportPath}'` : '';
      },
    )
    .replace(/^const meta:\s*Meta<[\s\S]*?^export default meta\s*$/gm, '')
    .replace(/^type Story\s*=\s*StoryObj<[\s\S]*?^\s*$/gm, '')
    .replace(/export const (\w+)\s*:\s*Story\s*=/g, 'export const $1 =')
    .trim();
}

export function extractMetaComponent(source: string) {
  const match = source.match(/component:\s*([A-Za-z$_][\w$]*)/);
  return match?.[1] ?? null;
}

function extractMetaValue(source: string, key: string) {
  const match = source.match(new RegExp(`${key}:\\s*'([^']+)'`));
  return match?.[1] ?? null;
}

function extractStorybookTitle(source: string | null) {
  if (!source) {
    return null;
  }

  const match = source.match(/title:\s*['"`]([^'"`]+)['"`]/);
  return match?.[1] ?? null;
}

function getNodeDescription(node: ts.Node) {
  const comments = ts.getJSDocCommentsAndTags(node);
  const parts: string[] = [];

  for (const comment of comments) {
    if (ts.isJSDoc(comment) && typeof comment.comment === 'string') {
      parts.push(comment.comment.trim());
    }
  }

  const description = parts.join('\n').trim();
  return description.length > 0 ? description : null;
}

function getNodeDefaultValue(node: ts.Node) {
  for (const tag of ts.getJSDocTags(node)) {
    if (tag.tagName.text !== 'default') {
      continue;
    }

    const value = typeof tag.comment === 'string' ? tag.comment : tag.comment?.map((part) => part.text).join('');
    const normalised = value?.trim();
    if (normalised) {
      return normalised;
    }
  }

  return null;
}

function extractPropsFromComponentSource(sourcePath: string, componentName: string) {
  const source = ts.sys.readFile(sourcePath);
  if (!source) {
    return {
      inheritedPropsNote: null,
      props: [] as ComponentPropDoc[],
    };
  }

  const sourceFile = ts.createSourceFile(sourcePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const targetNames = new Set([
    `I${componentName.replace(/\s+/g, '')}Props`,
    `${componentName.replace(/\s+/g, '')}Props`,
  ]);

  let inheritedPropsNote: string | null = null;
  const props: ComponentPropDoc[] = [];

  const visit = (node: ts.Node) => {
    if ((ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) && targetNames.has(node.name.text)) {
      if (ts.isInterfaceDeclaration(node)) {
        inheritedPropsNote =
          node.heritageClauses
            ?.flatMap((clause) => clause.types.map((typeNode) => typeNode.getText(sourceFile)))
            .join(', ') ?? null;

        for (const member of node.members) {
          if (!ts.isPropertySignature(member) || !member.name) {
            continue;
          }

          props.push({
            defaultValue: getNodeDefaultValue(member),
            description: getNodeDescription(member),
            name: member.name.getText(sourceFile).replace(/['"]/g, ''),
            required: !member.questionToken,
            type: member.type?.getText(sourceFile) ?? 'unknown',
          });
        }
      } else if (ts.isTypeLiteralNode(node.type)) {
        for (const member of node.type.members) {
          if (!ts.isPropertySignature(member) || !member.name) {
            continue;
          }

          props.push({
            defaultValue: getNodeDefaultValue(member),
            description: getNodeDescription(member),
            name: member.name.getText(sourceFile).replace(/['"]/g, ''),
            required: !member.questionToken,
            type: member.type?.getText(sourceFile) ?? 'unknown',
          });
        }
      } else {
        inheritedPropsNote = node.type.getText(sourceFile);
      }
    }

    ts.forEachChild(node, visit);
  };

  visit(sourceFile);

  return {
    inheritedPropsNote,
    props,
  };
}

async function buildComponentRegistryEntries(componentDocs: ComponentDoc[]) {
  return Promise.all(
    componentDocs.map(async (doc) => {
      const docsSource = await readFile(doc.sourcePath, 'utf8');
      const storyPath = getSiblingPath(doc.sourcePath, '.stories.tsx');
      const componentDir = dirname(doc.sourcePath);
      const indexPath = join(componentDir, 'index.tsx');
      const fallbackIndexPath = join(componentDir, 'index.ts');
      const typesPath = join(componentDir, 'types.ts');

      const resolvedSourcePath = (await fileExists(indexPath)) ? indexPath : fallbackIndexPath;
      const hasStory = await fileExists(storyPath);
      const storySource = hasStory ? await readFile(storyPath, 'utf8') : null;
      const storyComponent = storySource ? extractMetaComponent(storySource) : null;
      const typesSource = (await fileExists(typesPath)) ? await readFile(typesPath, 'utf8') : '';
      const { props, inheritedPropsNote } = extractPropsFromComponentSource(
        resolvedSourcePath,
        doc.title,
      );

      return {
        description: doc.description,
        docsPath: doc.sourcePath,
        examples: parseCanvasExamples(docsSource, storySource, storyComponent ?? doc.title),
        href: doc.href,
        inheritedPropsNote,
        props,
        slug: doc.slug,
        sourcePath: resolvedSourcePath,
        status: extractMetaValue(typesSource, 'status'),
        storyPath: hasStory ? storyPath : null,
        storybookTitle: extractStorybookTitle(storySource),
        swiftui: extractMetaValue(typesSource, 'swiftui'),
        title: doc.title,
      } satisfies GeneratedComponentRegistryEntry;
    }),
  );
}

async function buildPreviewModules(entries: GeneratedComponentRegistryEntry[], previewDir: string) {
  const previews: PreviewModuleEntry[] = [];
  const uiRootExports = await loadUiRootExports(previewDir);
  const uiImportPath = '@swiftuijs/ui';

  for (const entry of entries) {
    if (!entry.storyPath) {
      continue;
    }

    const storySource = await readFile(entry.storyPath, 'utf8');
    const transformed = transformStorySourceForDocs(
      storySource,
      uiImportPath,
    );
    const importedSymbols = extractUiImports(transformed, uiImportPath);
    const metaComponent = extractMetaComponent(storySource);

    if ([...importedSymbols].some((symbol) => !uiRootExports.has(symbol))) {
      continue;
    }

    if (metaComponent && !uiRootExports.has(metaComponent)) {
      continue;
    }

    previews.push({
      slug: entry.slug,
      source: `// @ts-nocheck\n'use client';\n\n${transformed}${
        metaComponent ? `\n\nexport const __DOCS_COMPONENT__ = ${metaComponent};` : ''
      }`,
    });
  }

  return previews;
}

export async function writeComponentRegistry(options: {
  componentDocs: ComponentDoc[];
  outputPath: string;
  previewDir: string;
}) {
  const entries = await buildComponentRegistryEntries(options.componentDocs);
  const previews = await buildPreviewModules(entries, options.previewDir);
  const previewLookup = new Map(previews.map((preview) => [preview.slug, `() => import('./previews/${preview.slug}')`]));
  const registryObject = Object.fromEntries(entries.map((entry) => [entry.slug, entry]));

  await mkdir(options.previewDir, { recursive: true });
  await Promise.all(
    previews.map(async (preview) => {
      await mkdir(join(options.previewDir, dirname(preview.slug)), { recursive: true });
      await writeFileAtomic(join(options.previewDir, `${preview.slug}.tsx`), `${preview.source}\n`);
    }),
  );

  const body = [
    registryHeader,
    `export const componentDocRegistry = ${JSON.stringify(registryObject, null, 2)} as const;`,
    '',
    'export const componentPreviewRegistry = {',
    ...entries.map((entry) => {
      const preview = previewLookup.get(entry.slug);
      return `  '${entry.slug}': ${preview ?? 'null'},`;
    }),
    '} as const;',
    '',
  ].join('\n');

  await mkdir(dirname(options.outputPath), { recursive: true });
  await writeFileAtomic(options.outputPath, body);
}
